"""Cấu hình cố định cho ứng dụng giám sát miền Nam."""

APP_NAME = "TOMS SLA MN"
APP_SLUG = "TOMS-SLA-MN"
APP_DATA_ENV = "TOMS_SLA_MN_DATA_DIR"
TELEGRAM_TOKEN_ENV = "TOMS_SLA_MN_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ENV = "TOMS_SLA_MN_TELEGRAM_GROUP_CHAT_ID"
UNIT_LABEL = "Phòng HTKH Miền Nam (VIP 2)"
