"""Cấu hình cố định cho ứng dụng giám sát miền Nam."""

APP_NAME = "TOMS SLA MN"
APP_SLUG = "TOMS-SLA-MN"
APP_DATA_ENV = "TOMS_SLA_MN_DATA_DIR"
TELEGRAM_TOKEN_ENV = "TOMS_SLA_MN_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ENV = "TOMS_SLA_MN_TELEGRAM_GROUP_CHAT_ID"
SERVICE_CATALOG_API_URL = "https://script.google.com/macros/s/AKfycbwezDNYkDoc7qPF4rhwWgqcUjL4FYCVVS_Iu0p9YOG2Qe5MR7U0onGc0yMNV2DqxU0Xpg/exec"
UNIT_LABEL = "Phòng HTKH Miền Nam (VIP 2)"
